### ISSUE TITLE
TypeError: init_weights() missing 1 required positional argument: 'module'

### ISSUE THREAD

**Issue by XuJianzhi** [GT-SALT/MixText#25]
python ./code/normal_train.py --gpu 0,1 --n-labeled 10 --data-path ./data/yahoo_answers_csv/ \
--batch-size 8 --epochs 20 

python ./code/train.py --gpu 0,1 --n-labeled 10 --data-path ./data/yahoo_answers_csv/ \
--batch-size 8 --batch-size-u 1 --epochs 50 --val-iteration 20 \
--lambda-u 0 --T 0.5 --alpha 16 --mix-layers-set 7 9 12 --separate-mix True 

Traceback (most recent call last):
  File "./code/train.py", line 451, in <module>
    main()
  File "./code/train.py", line 112, in main
    model = MixText(n_labels, args.mix_option).cuda()
  File "/xxxxx/MixText-master/code/mixtext.py", line 172, in __init__
    self.bert = BertModel4Mix.from_pretrained('bert-base-uncased')
  File "/xxxxx/MixText-master/venv/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 474, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/xxxxx/MixText-master/code/mixtext.py", line 17, in __init__
    self.init_weights()
TypeError: init_weights() missing 1 required positional argument: 'module'

**Comment by XuJianzhi** [comment]
It's ok with pytorch-transformers==1.2.0 ~~~~~~~~
